# Generated by Django 5.0.14 on 2025-10-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_slug_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
