# Generated by Django 5.0.14 on 2025-10-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
    ]
