# Generated by Django 5.0.14 on 2025-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tag_slug_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, through='core.Project_tags', to='core.tag'),
        ),
    ]
