# Generated by Django 5.0.14 on 2025-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_views_count_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
