# Generated by Django 5.0.14 on 2025-10-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
