# Generated by Django 5.0.14 on 2025-10-06 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_remove_feedback_email_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='demo_url',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.solution'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='solution',
            name='faqs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='solution',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='solution',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solution',
            name='use_cases',
            field=models.JSONField(default=list),
        ),
    ]
