# Generated by Django 5.2.5 on 2025-09-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='featured_image',
        ),
    ]
