# Generated by Django 5.2.4 on 2025-09-02 10:43

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_options_blog_published_at_blog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.blog_upload_to),
        ),
    ]
