# Generated by Django 5.2.4 on 2025-09-02 10:43

import django.utils.timezone
import solutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwaresolution',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='softwaresolution',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='softwaresolution',
            name='industry',
        ),
        migrations.AddField(
            model_name='softwaresolution',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='softwaresolution',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwaresolution',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='softwaresolution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='softwaresolution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=solutions.models.solution_upload_to),
        ),
        migrations.AlterField(
            model_name='softwaresolution',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='softwaresolution',
            index=models.Index(fields=['slug'], name='solutions_s_slug_5e93d5_idx'),
        ),
        migrations.AddIndex(
            model_name='softwaresolution',
            index=models.Index(fields=['status', 'published_at'], name='solutions_s_status_9afd97_idx'),
        ),
    ]
