# Generated by Django 5.2.4 on 2025-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_softwaresolution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaresolution',
            name='demo_link',
            field=models.URLField(blank=True, help_text='Optional demo URL for this solution', null=True),
        ),
    ]
